# Dependencies

In [1]:
import gym
from gym import Env
from gym.spaces import Discrete, Box, Dict, Tuple, MultiBinary, MultiDiscrete

import numpy as np
import random
import os

from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

# Types of Spaces

In [7]:
# 0, 1, 2
Discrete(3).sample()

2

In [10]:
# An array 3 x 3 (an array that contains 3 arrays with each array containing 3 values)
# 0 and 1 are the lower and upper values (the range of where the values will lie)
Box(0,1,shape=(3,3)).sample()

array([[0.11172476, 0.13338836, 0.675468  ],
       [0.09634547, 0.6680662 , 0.38782513],
       [0.8826869 , 0.14965059, 0.20709646]], dtype=float32)

In [25]:
# Wrapper 1 that brings spaces together
Tuple((Discrete(3), Box(0,1,shape=(3,3)), MultiBinary(4))).sample()

(1,
 array([[0.72381985, 0.75307155, 0.836142  ],
        [0.75173223, 0.91596746, 0.18010943],
        [0.66017056, 0.07019453, 0.7298493 ]], dtype=float32),
 array([1, 0, 0, 1], dtype=int8))

In [20]:
# Wrapper 2 that brings spaces together
Dict({'height':Discrete(2), 'speed':Box(0,100,shape=(1,))}).sample()

OrderedDict([('height', 1), ('speed', array([19.978773], dtype=float32))])

In [17]:
# Contains 4 positions
MultiBinary(4).sample()

array([1, 1, 0, 1], dtype=int8)

In [19]:
MultiDiscrete([5,2,2]).sample()

array([2, 1, 0], dtype=int64)

# Building Environment

# Testing the Environment

# Train the Model

# Save the Model